# Generated by Django 4.1.5 on 2023-01-30 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departmemt',
            new_name='department',
        ),
    ]
